services:
  server:
    build: .
    restart: unless-stopped
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"